In [1]:
def square(number = 3):
    """
    This is a docstring. 
    When you clicking shift+tab, then you get detailed information about this function
    """
   

    return number**2

In [2]:
example = square(5)

In [3]:
example

25

In [4]:
ll = square()

In [5]:
ll

9

In [7]:
def times(num):
    return num*2

In [9]:
# map()

seq = [1,2,3,4,5]

In [10]:
seq = [1,2,3,4,5]

In [12]:
list(map(times, seq))

[2, 4, 6, 8, 10]

In [13]:
t = lambda var: var**2

In [15]:
t(4)

16

In [18]:
list(map(lambda num: num+5, seq))

[6, 7, 8, 9, 10]

In [19]:
list(filter(lambda num: num%2 == 0, seq))

[2, 4]

In [20]:
s = "hello, my name is Pine, how are you"

In [22]:
s.lower()

'hello, my name is pine, how are you'

In [23]:
s.split()

['hello,', 'my', 'name', 'is', 'Pine,', 'how', 'are', 'you']

In [24]:
s[3]

'l'

In [25]:
tweet = "Go Subway, #Sports"

In [30]:
tweet.split('#')[1]

'Sports'

In [31]:
 'x' in ['x', 1, 2, 3]

True

In [32]:
'x' in [1, 3]

False

In [33]:
x = [(1,2), (3,4), (5,6)]

In [34]:
x[0]

(1, 2)

In [35]:
for item in x:
    print(item)

(1, 2)
(3, 4)
(5, 6)


In [37]:
for (a,b) in x:
    print (a)

1
3
5


In [3]:
import numpy as np

In [4]:
myList = [12, 3,34]

In [5]:
np.arange(0,12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [6]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [11]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
np.arange(1,20,2
         )

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [15]:
np.zeros(4)

array([0., 0., 0., 0.])

In [17]:
np.zeros((4,1))

array([[0.],
       [0.],
       [0.],
       [0.]])

In [18]:
np.ones(3)

array([1., 1., 1.])

In [19]:
np.ones((3,4
    ))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [22]:
np.random.rand(4)

array([0.34491437, 0.2858262 , 0.75851784, 0.42146144])

In [23]:
np.random.randn(4)

array([ 2.28208391, -1.06102365,  0.08435586,  1.24415108])

In [29]:
np.random.randint(1,10)

7

In [30]:
np.random.randint(1,10,3)

array([3, 2, 1])

In [31]:
arr

NameError: name 'arr' is not defined

In [32]:
arr = np.arange(10)

In [33]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
arr.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [35]:
arr[:,3]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [39]:
arr[1,2]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [40]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
arr = arr.reshape(2,5)

In [42]:
arr



array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [43]:
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [44]:
arr[:,2]

array([2, 7])

In [45]:
arr[:3] = 100

In [46]:
arr

array([[100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100]])

In [47]:
arr

array([[100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100]])

In [48]:
arr = np.arange(10)

In [49]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
arr[4] = 100

In [53]:
arr

array([  0,   1,   2,   3, 100,   5,   6,   7,   8,   9])

In [54]:
arr

array([  0,   1,   2,   3, 100,   5,   6,   7,   8,   9])

In [57]:
arr[:3]

array([0, 1, 2])

In [63]:
array = arr[:3]

In [64]:
array

array([0, 1, 2])

In [65]:
array[:] = 100

In [66]:
array

array([100, 100, 100])

In [67]:
arr

array([100, 100, 100,   3, 100,   5,   6,   7,   8,   9])

In [70]:
some = arr.copy()

In [71]:
some

array([100, 100, 100,   3, 100,   5,   6,   7,   8,   9])

In [72]:
some[:] = 200

In [73]:
some

array([200, 200, 200, 200, 200, 200, 200, 200, 200, 200])

In [74]:
arr

array([100, 100, 100,   3, 100,   5,   6,   7,   8,   9])

In [75]:
ax = np.arange(25)

In [76]:
ax

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [77]:
ax = ax.reshape(5,5)

In [78]:
ax

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [79]:
ax.argmin()

0

In [80]:
ax.argmax()

24

In [82]:
ax.max()

24

In [83]:
ax

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [84]:
ax.shape

(5, 5)

In [85]:
arr.dtype


dtype('int32')

In [86]:
ax.dtype

dtype('int32')

In [87]:
arrList = [[2,3,4],[23,43,34]]

In [88]:
arrList

[[2, 3, 4], [23, 43, 34]]

In [89]:
np.array(arrList
        )

array([[ 2,  3,  4],
       [23, 43, 34]])

In [91]:
jk = np.zeros((10,10))

In [92]:
jk

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [97]:
arr_length = jk.shape[1]

In [98]:
arr_length

10

In [102]:
for i in range(arr_length):
    jk[i] = i

In [99]:
dd = range(5)

In [101]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [103]:
jk

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [105]:
jk[2]

array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])

In [108]:
jk[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [110]:
#Allows in any order
jk[[6,4,2,7]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])